In [1]:
import math
from scipy.optimize import minimize
import numpy as np

In [2]:
### tools：

def minfunction(f, x0, bounds):
    """
    求一个函数在边界内的最小值
    f：函数
    x0：初始值
    bounds：边界条件。[(min, max),...]
    """
    res = minimize(f, x0, method='SLSQP', bounds=bounds)
    return res

def maxfunction(f, x0, bounds):
    """
    求一个函数在边界内的最大值
    f：函数
    x0：初始值
    bounds：边界条件。[(min, max),...]
    """
    fun = lambda X : -f(X)
    res = minimize(fun, x0, method='SLSQP', bounds=bounds)
    return res


In [3]:
### 目标函数：
bounds = [(704.4148,906.3855),(68.6,288.88),(0,134.75),(193,287.0966),(25,84.1988)]
x_opt = [705.174537070090537, 68.5999999999999943, 102.899999999999991, 282.324931593660324, 37.5841164258054832]
y_opt = -1.90515525853479
def G16(X):
    y1 = X[1] +X[2]+41.6
    c1 = 0.024*X[3]-4.62
    y2= 12.5/c1 + 12
    c2 = 0.0003535*X[0]**2 + 0.5311*X[0] + 0.08705*y2*X[0]
    c3 = 0.052*X[0] + 78 + 0.002377*y2*X[0]
    y3 = c2/c3
    y4 = 19*y3
    c4 = 0.04782*(X[0]-y3)+0.1956*(X[0]-y3)**2 / X[1] + 0.6376*y4 + 1.594*y3
    c5 = 100*X[1]
    c6 = X[0]-y3-y4
    c7 = 0.950-c4/c5
    y5 = c6*c7
    y6 = X[0]-y5-y4-y3
    c8 = (y5+y4)*0.995
    y7 = c8/y1
    y8 = c8/3798
    c9 = y7 - 0.0663*y7/y8-0.3153
    y9 = 96.82/c9+0.321*y1
    y10 = 1.29*y5+1.258*y4+2.29*y3+1.71*y6
    y11 = 1.71*X[0]-0.452*y4+0.580*y3
    c10 = 12.3/752.3
    c11 = 1.75*y2*0.995*X[0]
    c12 = 0.995*y10+1998
    y12 = c10*X[0]+c11/c12
    y13 = c12-1.75*y2
    y14 = 3623+64.4*X[1]+58.4*X[2]+146312/(y9+X[4])
    c13 = 0.995*y10+60.8*X[1]+48*X[3]-0.1121*y14-5095
    y15 = y13/c13
    y16 = 148000 - 331000*y15 + 40*y13 - 61*y15*y13
    c14 = 2324*y10 - 28740000*y2
    y17 = 14130000-1328*y10-531*y11+c14/c12
    c15 = y13/y15 - y13/0.52
    c16 = 1.104 - 0.72*y15
    c17 = y9+X[4]
    y = 0.000117*y14+0.1365+0.00002358*y13 + 0.000001502*y16+0.0321*y12+0.004324*y5+0.0001*c15/c16+37.48*y2/c12-0.0000005843*y17
    g1 = 0.28*y5/0.72-y4
    g2 = X[2]-1.5*X[1]
    g3 = 3496*y2/c12-21
    g4 = 110.6+y1-62212/c17
    g5 = 213.1-y1
    g6 = y1-405.23
    g7 = 17.505-y2
    g8 = y2-1053.6667
    g9 = 11.275-y3
    g10 = y3-35.03
    g11 = 214.228-y4
    g12 = y4-665.585
    g13 = 7.458-y5
    g14 = y5-584.463
    g15 = 0.961-y6
    g16 = y6-265.916
    g17 = 1.612-y7
    g18 = y7-7.046
    g19 = 0.146-y8
    g20 = y8-0.222
    g21 = 107.99-y9
    g22 = y9-273.366
    g23 = 922.693-y10
    g24 = y10-1286.105
    g25 = 926.832-y11
    g26 = y11-1444.046
    g27 = 18.766-y12
    g28 = y12-537.141
    g29 = 1072.163-y13
    g30 = y13-3247.039
    g31 =  8961.448-y14
    g32 = y14-26844.086
    g33 = 0.063-y15
    g34 = y15-0.386
    g35 = 71084.33-y16
    g36 = -140000+y16
    g37 = 2802713-y17
    g38 = y17-12146108
    return y,g1,g2,g3,g4,g5,g6,g7,g8,g9,g10,g11,g12,g13,g14,g15,g16,g17,g18,g19,g20,g21,g22,g23,g24,g25,g26,g27,g28,g29,g30,g31,g32,g33,g34,g35,g36,g37,g38

In [4]:
# y = lambda X : G16(X)[0]
# g1 = lambda X : G16(X)[1]
# g2 = lambda X : G16(X)[2]
# g3 = lambda X : G16(X)[3]
# g4 = lambda X : G16(X)[4]
# g5 = lambda X : G16(X)[5]
# g6 = lambda X : G16(X)[6]
# g7 = lambda X : G16(X)[7]
# g8 = lambda X : G16(X)[8]
# g9 = lambda X : G16(X)[9]
# g10 = lambda X : G16(X)[10]
# g11 = lambda X : G16(X)[11]
# g12 = lambda X : G16(X)[12]
# g13 = lambda X : G16(X)[13]
# g14 = lambda X : G16(X)[14]
# g15 = lambda X : G16(X)[15]
# g16 = lambda X : G16(X)[16]
# g17 = lambda X : G16(X)[17]
# g18 = lambda X : G16(X)[18]
# g19 = lambda X : G16(X)[19]
# g20 = lambda X : G16(X)[20]
# g21 = lambda X : G16(X)[21]
# g22 = lambda X : G16(X)[22]
# g23 = lambda X : G16(X)[23]
# g24 = lambda X : G16(X)[24]
# g25 = lambda X : G16(X)[25]
# g26 = lambda X : G16(X)[26]
# g27 = lambda X : G16(X)[27]
# g28 = lambda X : G16(X)[28]
# g29 = lambda X : G16(X)[29]
# g30 = lambda X : G16(X)[30]
# g31 = lambda X : G16(X)[31]
# g32 = lambda X : G16(X)[32]
# g33 = lambda X : G16(X)[33]
# g34 = lambda X : G16(X)[34]
# g35 = lambda X : G16(X)[35]
# g36 = lambda X : G16(X)[36]
# g37 = lambda X : G16(X)[37]
# g38 = lambda X : G16(X)[38]
# x0 = [800,100,100,200,60]
# x0 = [705,68.6,0,193,25]
# x0 = [906,288,134,287,84]

In [5]:
# maxfunction(g38,x0,bounds)

     fun: 10051.457504168153
     jac: array([2544.125,  -25.5  ,    0.   , -498.   ,    0.   ])
 message: 'Optimization terminated successfully'
    nfev: 12
     nit: 3
    njev: 2
  status: 0
 success: True
       x: array([704.4148, 288.88  , 134.    , 287.0966,  84.    ])

In [6]:
# -20.632818745090447+31.85000000000001+1242.2302468633493+423.171523587728+102.9+59.999999999913825
# +8.423273687638243+50.84204062512838+49.959246237629486+3785.722540127488+67845.33423414978+440245.222393902

511985.5037287297

In [7]:
### 适应度函数
def fitnessG16_num(X):
    """
    problem1关于数量惩罚的适应度函数
    X: 对应的解
    epsion：惩罚系数大于fmax-fmin的倍数
    """
    fmax = 34.7078246512734
    fmin = 0.008509619375000003
    count = np.sum(np.array(problem1(X))[1:5]>0)
    
    return -(problem1(X)[0]+epsion*(fmax-fmin)*count)  

def fitnessG16_vio(X):
    """
    problem1关于数量惩罚的适应度函数
    X: 对应的解
    epsion：惩罚系数大于fmax-fmin的倍数
    """
    fmax = 34.7078246512734
    fmin = -2.6926825010757085
    vmax = 512000.5037287297
    e = 0.0001
    n = 38
    
    res = G16(X)
    fitness = -res[0]
    count = np.sum(np.array(res)[1:39]>0)
    
    
    if count > 0:
        for i in range(1,len(res)):
            if res[i] > 0:
                cathy = (fmax - fmin)*(e*vmax*n/count+res[i])/(e*vmax)
                fitness = fitness - cathy
    return fitness   


In [8]:
### PSO
class PSO_fit():
    def __init__(self, pN, dim, max_iter, bounds):
        self.wmax = 0.8 #最大的惯性权重
        self.wmin = 0.4 #最小的惯性权重
        self.c1 = 2  #加速因子
        self.c2 = 2  #加速因子
        self.pN = pN  # 粒子数量
        self.dim = dim  # 搜索维度
        self.max_iter = max_iter  # 迭代次数
        self.bounds = bounds
        
        self.X = np.zeros((self.pN, self.dim))  # 所有粒子的位置：一个pN*dim的矩阵
        self.V = np.zeros((self.pN, self.dim))  # 左右粒子的速度：一个pN*dim的矩阵
        self.pbest = np.zeros((self.pN, self.dim))  # 个体经历的最佳位置：一个pN*dim的矩阵
        self.gbest = np.zeros((self.pN, self.dim))      # 全局最佳位置：一个pN*dim的矩阵
        self.p_fit = np.full(self.pN,-10.0e+28)  # 每个个体的历史最佳适应值
        self.g_fit = np.full(self.pN,-10.0e+28)    # 全局最佳适应值
    
    def init_Population(self):
        """
        初始化种群
        :return:
        """
        
        for i in range(self.pN):
            for j in range(self.dim):
                self.X[i][j] = self.bounds[j][0] + (self.bounds[j][1] - self.bounds[j][0]) * np.random.random()
                self.V[i][j] = self.bounds[j][0] + (self.bounds[j][1] - self.bounds[j][0]) * np.random.random()
        for i in range(self.pN):
            tmp = fitnessG16_vio(self.X[i])
            if (tmp > self.p_fit[i]):
                self.p_fit[i] = tmp
                self.pbest[i] = self.X[i]
                
        for i in range(self.pN):
            indexes = np.random.randint(low=0,high=self.pN,size=int(self.pN/100))
            for j in indexes:
                if self.p_fit[j] > self.g_fit[i]:
                    self.g_fit[i] = self.p_fit[j]
                    self.gbest[i] = self.pbest[j]

#             self.pbest[i] = self.X[i]
#             tmp = fitnessG01_num(self.X[i])
#             self.p_fit[i] = tmp
#             if (tmp > self.fit):
#                 self.fit = tmp
#                 self.gbest = self.X[i]
        
    def iterator(self):
        """
        迭代
        """
        for t in range(self.max_iter):
            w = self.wmin + (self.wmax - self.wmin) * np.exp(- (4 * t / self.max_iter) * (4 * t / self.max_iter))
            
            for i in range(self.pN):
                self.V[i] = w*self.V[i]+self.c1*np.random.random()*(self.pbest[i]-self.X[i])+self.c2*np.random.random()*(self.gbest[i]-self.X[i])
                self.X[i] = self.X[i] + self.V[i]
                
                """
                控制在搜索范围内
                """ 
                for j in range(self.dim):
                    if self.X[i][j] < self.bounds[j][0]:
                        self.X[i][j] = self.bounds[j][0]
                    if self.X[i][j] > self.bounds[j][1]:
                        self.X[i][j] = self.bounds[j][1]     
            for i in range(self.pN):
                tmp = fitnessG16_vio(self.X[i])
                if (tmp > self.p_fit[i]):
                    self.p_fit[i] = tmp
                    self.pbest[i] = self.X[i]
            for i in range(self.pN):
                indexes = np.random.randint(low=0,high=self.pN,size=int(self.pN/100))
                for j in indexes:
                    if self.p_fit[j] > self.g_fit[i]:
                        self.g_fit[i] = self.p_fit[j]
                        self.gbest[i] = self.pbest[j]
            print(self.g_fit)  
        return self.gbest, self.g_fit

In [9]:
PSO = PSO_fit(pN=4000, dim=5, max_iter=1000, bounds=bounds)

In [10]:
PSO.init_Population()

In [11]:
PSO.iterator()

[-1436.34490454 -1426.42054267 -1424.77952885 ... -1425.41256672
 -1438.53862664 -1420.79389959]
[-1420.28915032 -1423.08048991 -1423.90791773 ... -1423.13053624
 -1424.36112137 -1420.79389959]
[-1420.28915032 -1420.07434986 -1421.78040572 ... -1423.13053624
 -1423.13401789 -1420.79389959]
[-1420.28915032 -1419.99810385 -1421.78040572 ... -1420.95687381
 -1420.63944524 -1420.79389959]
[-1420.28915032 -1419.99810385 -1419.97317566 ... -1420.95687381
 -1420.03011783 -1420.25184208]
[-1420.01994445 -1419.84112567 -1419.97317566 ... -1420.11506163
 -1420.03011783 -1420.25184208]
[-1420.01994445 -1419.84112567 -1419.97317566 ... -1419.86843644
 -1419.96203766 -1419.97158541]
[-1419.9400254  -1419.84112567 -1419.92790634 ... -1419.86843644
 -1419.93103218 -1419.97158541]
[-1419.85658594 -1419.84112567 -1419.92790634 ... -1419.86843644
 -1419.85658594 -1419.97158541]
[-1419.85658594 -1419.84112567 -1419.92790634 ... -1419.86843644
 -1419.85658594 -1419.91635528]
[-1.41985659e+03 -1.41984113e+

[1.90189352 1.90233817 1.90297543 ... 1.90270323 1.90272731 1.90304181]
[1.9026177  1.9025868  1.90297543 ... 1.90270323 1.90272731 1.90304181]
[1.9026177  1.90286345 1.90297543 ... 1.90270323 1.90272731 1.90304181]
[1.9026177  1.90286345 1.90297543 ... 1.90270323 1.90272731 1.90304181]
[1.9026177  1.90286345 1.90297543 ... 1.90270323 1.90272731 1.90304181]
[1.90302626 1.90298838 1.90297543 ... 1.90300307 1.90272731 1.90304181]
[1.90302626 1.90298838 1.90297543 ... 1.90300307 1.90272731 1.90304181]
[1.90302626 1.90337507 1.90301324 ... 1.90307148 1.90328979 1.90304181]
[1.90305432 1.90337507 1.90301324 ... 1.90311077 1.90328979 1.90304181]
[1.90305432 1.90337507 1.90328979 ... 1.90311077 1.90328979 1.90304181]
[1.90305432 1.90342992 1.90328979 ... 1.90311077 1.90328979 1.90304181]
[1.90341599 1.90342992 1.90341164 ... 1.90311077 1.90328979 1.90304181]
[1.90341599 1.90342992 1.90341164 ... 1.90311077 1.90342992 1.90368603]
[1.90341599 1.90342992 1.90341164 ... 1.90404659 1.90342992 1.90

[1.90515203 1.90515204 1.90515208 ... 1.90515209 1.90515215 1.90515335]
[1.90515203 1.90515204 1.90515335 ... 1.90515209 1.90515215 1.90515335]
[1.90515296 1.90515204 1.90515335 ... 1.90515209 1.90515215 1.90515335]
[1.90515296 1.90515204 1.90515335 ... 1.90515209 1.90515215 1.90515335]
[1.90515296 1.90515204 1.90515335 ... 1.90515209 1.90515215 1.90515335]
[1.90515296 1.90515204 1.90515335 ... 1.9051525  1.90515215 1.90515335]
[1.90515296 1.90515204 1.90515335 ... 1.9051525  1.90515264 1.90515335]
[1.90515296 1.90515234 1.90515335 ... 1.9051525  1.90515264 1.90515335]
[1.90515296 1.90515259 1.90515366 ... 1.9051542  1.90515287 1.90515335]
[1.90515296 1.9051541  1.90515366 ... 1.9051542  1.90515287 1.90515335]
[1.90515296 1.9051541  1.90515366 ... 1.9051542  1.90515287 1.90515383]
[1.90515368 1.9051541  1.90515366 ... 1.9051542  1.90515287 1.90515383]
[1.90515368 1.9051541  1.90515385 ... 1.90515428 1.90515449 1.90515383]
[1.90515395 1.9051541  1.90515395 ... 1.90515428 1.90515461 1.90

[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90

[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90

[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90

[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90

[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90

[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90515526]
[1.90515526 1.90515526 1.90515526 ... 1.90515526 1.90515526 1.90

(array([[705.17453707,  68.6       , 102.9       , 282.32493159,
          37.58411643],
        [705.17453707,  68.6       , 102.9       , 282.32493159,
          37.58411643],
        [705.17453707,  68.6       , 102.9       , 282.32493159,
          37.58411643],
        ...,
        [705.17453707,  68.6       , 102.9       , 282.32493159,
          37.58411643],
        [705.17453707,  68.6       , 102.9       , 282.32493159,
          37.58411643],
        [705.17453707,  68.6       , 102.9       , 282.32493159,
          37.58411643]]),
 array([1.90515526, 1.90515526, 1.90515526, ..., 1.90515526, 1.90515526,
        1.90515526]))