In [1]:
import pandas as pd
import numpy as np

In [2]:
data1 = pd.read_excel("./Book1_100.xlsx", dtype="str")
# data2 = pd.read_excel("./Book2.xlsx", dtype="str")
data2 = pd.read_excel("./Book4_100.xlsx", dtype="str")

In [3]:
# 1vs2
better_count = np.zeros((6))
worst_count = np.zeros((6))
equal_count = np.zeros((6))
for i in range(28):
    for j in range(6):
        if '/' in data1.values[j][i]:
            if '/' in data2.values[j][i]:
                funs1, vios1 = data1.values[j][i].split('/', 1)
                funs2, vios2 = data2.values[j][i].split('/', 1)
                if float(funs1) < float(funs2): #and float(vios1) < float(vios2):
                    better_count[j] += 1
                elif float(funs1) > float(funs2): #and float(vios1) > float(vios2):
                    worst_count[j] += 1
                else:
                    equal_count[j] += 1
            else:
                worst_count[j] += 1
        else:
            if '/' in data2.values[j][i]:
                better_count[j] += 1
                # if j == 3:
                #     print(data1.values[j][i])
                #     print(data2.values[j][i])
                #     print(i)
            else:
                if float(data1.values[j][i]) < float(data2.values[j][i]):
                    better_count[j] += 1
                    # if j == 3:
                    #     print(float(data1.values[j][i]))
                    #     print(float(data2.values[j][i]))
                    #     print(i)
                elif float(data1.values[j][i]) > float(data2.values[j][i]):
                    worst_count[j] += 1
                else:
                    equal_count[j] += 1

print(better_count)
print(worst_count)
print(equal_count)

[ 5. 18. 17. 15. 17. 15.]
[ 2.  9. 11. 12. 11. 13.]
[21.  1.  0.  1.  0.  0.]
